# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: safe-UR-chain
claim: 'Sicherheit und Nachverfolgbarkeit in zivilen Produktions- und Wertschöpfungsnetzwerken durch Blockchain'
author: Adrian Singer
email: adrian.singer@iwu.fraunhofer.de
description: > # this means to ignore newlines until "baseurl:"
  Das vom BMBF geförderte Projekt safe-UR-chain befasst sich mit der Sicherstellung angriffs- und fälschungssicherer Datenströme innerhalb eines Unternehmens und in Wertschöpfungsnetzwerken.

baseurl: "/"

sass:
    style: compressed

highlighter: rouge

permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jemoji
  
# Build settings
markdown: kramdown
exclude: ["README.md"]